const n = Number(require('fs').readFileSync('/dev/stdin').toString().trim());
console.log(' @@@   @@@  '.repeat(n));
console.log('@   @ @   @ '.repeat(n));
console.log('@    @    @ '.repeat(n));
console.log('@         @ '.repeat(n));
console.log(' @       @  '.repeat(n));
console.log('  @     @   '.repeat(n));
console.log('   @   @    '.repeat(n));
console.log('    @ @     '.repeat(n));
console.log('     @      '.repeat(n));
